### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Anarchist-byte** [KarmaConfigs/page#11]
How to use MYSQL database in this plugin?

**Comment by KarmaConfigs** [comment]
> How to use MYSQL database in this plugin?

LockLogin?
First of all, [configure LockLogin to use MySQL](https://github.com/KarmaConfigs/page/wiki/Account-system-management), (restart the server / reload the plugin)
After reloading the plugin you will see a new file at LockLogin's folder, called mysql.yml
```yaml
MySQL:
  host: 'localhost' #--> Your MYSQL host
  database: 'server_users' #--> MySQL database name
  port: 3306 #--> MySQL host port
  table: 'users' #--> MySQL table
  user: 'root' #--> MySQL user
  password: 'MYSECUREPASSWORD' #--> MySQL user password
  SSL: false #--> (If your host has and supports SSL (https) set this to true)
Connection: #(Do not change this if you don't know what are you doing)
  Min: 3 #--> Minimum connections that must be alive
  Max: 10 #--> Maximum connections that can be alive
  TimeOut: 40 #--> Connection timeout
  LifeTime: 300 #--> Connections life time
```
