### ISSUE TITLE
everything is black

### ISSUE THREAD

**Issue by SuperSpaceMC** [KarmaConfigs/page#12]
during login
![image](https://user-images.githubusercontent.com/67235233/100241290-fa66e780-2f4c-11eb-9ca5-7d6eb0ba3002.png)
if left the game without being logined
![image](https://user-images.githubusercontent.com/67235233/100241439-1e2a2d80-2f4d-11eb-981a-9de76a101c54.png)

**Comment by KarmaConfigs** [comment]
That's a login option, check plugin config to disable it

(config.yml)
```yaml
Login:
  Blind: true --> Here
  Nausea: true --> And here
  TimeOut: 30
  MaxTries: 5
```
