### ISSUE TITLE
Bug con LockLogin

### ISSUE THREAD

**Issue by CroaBeast** [KarmaConfigs/page#7]
Hola, he tenido un problema al momento de logearme. A veces al entrar y usar /login, mi personaje se queda trabado y no se puede mover. Se arregla saliendo del servidor y volviendo a entrar, pero me gustaría saber si hay una manera de como arreglarlo definitivamente.

**Comment by KarmaConfigs** [comment]
> Hola, he tenido un problema al momento de logearme. A veces al entrar y usar /login, mi personaje se queda trabado y no se puede mover. Se arregla saliendo del servidor y volviendo a entrar, pero me gustaría saber si hay una manera de como arreglarlo definitivamente.

Usas algún plugin parecido o usas ExploitFixer?

**Comment by CroaBeast** [comment]
¿Algún plugin parecido de Logeo? No, uso más bien una extensión que apareción en su página de Spigot sobre Premium Login, pero más que eso, no.
Y ExploitFixer, honestamente he querido instalarlo pero siempre se me pasa. No tengo ExploitFixer instalado, y el bug persiste.

**Comment by KarmaConfigs** [comment]
Prueba sin usar PremiumLogin

**Comment by CroaBeast** [comment]
Listo, he reiniciado los 2 servers y el Bungeecord sin el PremiumLogin, y cuando entro me sigo quedando bugeado sin poder moverme. Luego como dije, se 'arregla' cuando salgo y vuelvo a entrar.

**Comment by KarmaConfigs** [comment]
Sale algún mensaje en la consola?

**Comment by CroaBeast** [comment]
No, hasta donde he visto en los logs de la consola, ya sea de Bungee o los otros serves, no aparece nada fuera de lo ordinario.

**Comment by KarmaConfigs** [comment]
Que versión de spigot estás usando?

**Comment by CroaBeast** [comment]
1.15.2
Si fuera Paper o Bukkit, ¿habría alguna diferencia?

**Comment by KarmaConfigs** [comment]
En Bukkit digamos que LockLogin no va muy bien, en cuanto a Paper, no debería haber ningún problema, el problema puede ser la versión, prueba a ver si ocurre lo mismo en alguna versión inferior

**Comment by CroaBeast** [comment]
No he encontrado una versión antigua para la 1.15 de PaperMC, ¿estoy probando con su versión más reciente (1.15.2). Si conoce el link del PaperMC de la 1.15, podría pasarlo por favor.

**Comment by KarmaConfigs** [comment]
https://yivesmirror.com/downloads/paper

**Comment by CroaBeast** [comment]
Estuve probando con las 3 primeras versiones que salieron de Paper para esa versión, incluso con la versión más reciente pero sigue pasando ese bug. ¿Puede ser algo de la configuración?

**Comment by KarmaConfigs** [comment]
Podría ser, has puesto LockLogin en todos los servidores?

**Comment by CroaBeast** [comment]
Si, en todos los servidores. No he tocado nada de esa configuración

**Comment by KarmaConfigs** [comment]
Puedo ver tu configuración?

**Comment by CroaBeast** [comment]
Este es la configuración de Bungee
```
ServerName: wqnfu
Register:
  TimeOut: 60
  Max: 2
Login:
  TimeOut: 30
  MaxTries: 5
Updater:
  CheckTime: 10
  ChangeLog: false
2FA: true
ClearChat: true
AccountsPerIp: 3
CheckNames: true
UseAuthLobby: true
Servers:
  AuthLobby: authlobby
  MainLobby: lobby
FallBack:
  AuthLobby: fbauth
  MainLobby: fblobby
Lang: en_EN
AccountSys: File
UseMainLobby: true
```
Este el del Lobby
```
ServerName: nkrwr
Register:
  Blind: true
  TimeOut: 60
  Max: 2
Login:
  Blind: true
  TimeOut: 30
  MaxTries: 5
Updater:
  CheckTime: 10
  ChangeLog: false
2FA: true
Spawn:
  Manage: true
  TakeBack: false
ClearChat: true
AccountsPerIp: 3
CheckNames: false
Lang: en_EN
AccountSys: File
BungeeProxy: '&cPlease, connect through bungeecord proxy!'
```
Y el de Survival
```
ServerName: chefr
Register:
  Blind: false
  TimeOut: 60
  Max: 2
Login:
  Blind: true
  TimeOut: 30
  MaxTries: 5
Updater:
  CheckTime: 10
  ChangeLog: false
2FA: true
Spawn:
  Manage: false
  TakeBack: false
ClearChat: true
AccountsPerIp: 3
CheckNames: false
Lang: en_EN
AccountSys: File
BungeeProxy: '&cPlease, connect through bungeecord proxy!'
```
